### ISSUE TITLE
NAS says "cannot retrieve app information list"

### ISSUE THREAD

**Issue by 3shirts** [goronu/Unofficial-QNAP-Plex-Repo#2]
I have added the repo (in fact I tried both your links to be sure) and both report this error and show no apps. I can install fine from the default repo and the MyQNAP one so it doesn't seem like a connectivity issue.
Thanks

**Comment by goronu** [comment]
Hi, sorry for late. I've corrected the script and repo files for older models of QNAP, I've added OLD_X86 model, I think that solve your issue.
Can you check ?
Thanks.

**Comment by 3shirts** [comment]
Hi. Thanks for the reply but still doesn't seem to work.

**Comment by goronu** [comment]
Can you re-check ? i've added TS-X70 platform ID.

**Comment by 3shirts** [comment]
Still no luck I'm afraid. For reference, the qpkg I manually install for Plex is PlexMediaServer-1.41.6.9685-d301f511a-x86_64

Does that help?

**Comment by goronu** [comment]
I've added TS-X79 plateform id, It share material base. What version of QTS do you have ?

**Comment by goronu** [comment]
I'm sure your nas use TS-NASX86... Can you try this repo address ? https://www.max-dev.ovh/repo/repo-test.xml

**Comment by 3shirts** [comment]
No luck there either. Strange

**Comment by goronu** [comment]
Verry strange... Can you make me a screenshot of error ? Every repo works on my TS-264...

**Comment by 3shirts** [comment]
Yeah, I am very confused why it's not working: https://i.postimg.cc/mRk3YPmp/image.png

I get that for the normal and test repos.

**Comment by 3shirts** [comment]
To try and narrow this down. I took the MyQNAP repo and modified an entry (Sonarr V4 Apache84) to be the current version of Plex. That worked.
I only changed the download link for the TS-NASX86 so that is clearly the right platform ID. There must be something else going on.
The file is here: https://limewire.com/d/LBvlj#TRBCy3bhCk

I'm trying to narrow down differences now.

**Comment by 3shirts** [comment]
Sorry to spam but **I've found the problem**. It's the stuff at the top of your xml, before the plugin tag. I took yours, removed that stuff and it worked!
